openshift310:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$CI_AUTH\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context 310 --dockerfile 310/Dockerfile --destination fchantada/openshift:310 --destination fchantada/openshift:latest
  only:
    refs:
      - master
      - schedules